/**
 * predictor.ts
 *
 * All prediction data is pre-generated by running:
 *   python generate_predictions.py
 *
 * That script calls the real ML model (lap_model.pkl) for every
 * track/car combo and writes the results to predictions.json.
 * This file just imports that JSON and looks up the right entry —
 * no backend needed, works on Vercel as a static site.
 */

import predictions from "./predictions.json";
import { TRACKS, CARS, ASCII_MAPS } from "./trackData";

export { TRACKS, CARS };

// ── Types ──────────────────────────────────────────────────────────────────

export interface CircuitResult {
  car_name: string;
  lap_time: number;
  lap_time_formatted: string;
  sector_1: number;
  sector_1_formatted: string;
  sector_2: number;
  sector_2_formatted: string;
  sector_3: number;
  sector_3_formatted: string;
  top_speed_kmh: number;
  avg_speed_kmh: number;
  confidence: string;
  is_rally?: false;
}

export interface RallyResult {
  car_name: string;
  stage_time: number;
  stage_time_formatted: string;
  ss1_formatted: string;
  ss2_formatted: string;
  ss3_formatted: string;
  top_speed_kmh: number;
  avg_speed_kmh: number;
  confidence: string;
  is_rally: true;
}

export type PredictionResult = CircuitResult | RallyResult;

// ── Main lookup ────────────────────────────────────────────────────────────

export function predict(
  category: string,
  trackId: string,
  carId: string
): PredictionResult | { error: string } {
  const catData = (predictions as Record<string, unknown>)[category];
  if (!catData) return { error: `Unknown category: ${category}` };

  const trackData = (catData as Record<string, unknown>)[trackId];
  if (!trackData) return { error: `No data for track: ${trackId}` };

  const cars = (trackData as { cars: Record<string, unknown> }).cars;
  const result = cars[carId];
  if (!result) return { error: `No data for car: ${carId}` };

  return result as PredictionResult;
}

// ── ASCII map lookup ───────────────────────────────────────────────────────

export function getAsciiMap(trackId: string): string {
  return (
    ASCII_MAPS[trackId] ??
    ASCII_MAPS[trackId.replace("_gt3", "").replace("_gt4", "")] ??
    ASCII_MAPS["default"] ??
    ""
  );
}
